//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncoderModbusTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncoderModbusTool.Properties.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 修改波特率异常: {0} 的本地化字符串。
        /// </summary>
        internal static string BaudRateChangeException {
            get {
                return ResourceManager.GetString("BaudRateChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string BaudRateChangeSuccess {
            get {
                return ResourceManager.GetString("BaudRateChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接关闭，请重新扫描设备！ 的本地化字符串。
        /// </summary>
        internal static string ConnectionClosedRescan {
            get {
                return ResourceManager.GetString("ConnectionClosedRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现设备 Slave ID={0} 的本地化字符串。
        /// </summary>
        internal static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备参数读取完成 的本地化字符串。
        /// </summary>
        internal static string DeviceParameterReadComplete {
            get {
                return ResourceManager.GetString("DeviceParameterReadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备(ID={0})参数读取失败 的本地化字符串。
        /// </summary>
        internal static string DeviceParameterReadFailed {
            get {
                return ResourceManager.GetString("DeviceParameterReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接编码器 (ID={0}) 的本地化字符串。
        /// </summary>
        internal static string EncoderConnected {
            get {
                return ResourceManager.GetString("EncoderConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现编码器，请重新扫描！ (ID={0}) 的本地化字符串。
        /// </summary>
        internal static string EncoderNotFound {
            get {
                return ResourceManager.GetString("EncoderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启后，自由模式将无法使用某些功能！！！ 的本地化字符串。
        /// </summary>
        internal static string FreeModeWarning {
            get {
                return ResourceManager.GetString("FreeModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率错误 的本地化字符串。
        /// </summary>
        internal static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave ID格式错误 的本地化字符串。
        /// </summary>
        internal static string InvalidSlaveIdFormat {
            get {
                return ResourceManager.GetString("InvalidSlaveIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式无效 的本地化字符串。
        /// </summary>
        internal static string InvalidWorkMode {
            get {
                return ResourceManager.GetString("InvalidWorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志已清除 的本地化字符串。
        /// </summary>
        internal static string LogCleared {
            get {
                return ResourceManager.GetString("LogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多圈位数已设置为 {0} bit 的本地化字符串。
        /// </summary>
        internal static string MultiTurnBitsSet {
            get {
                return ResourceManager.GetString("MultiTurnBitsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现设备 的本地化字符串。
        /// </summary>
        internal static string NoDeviceFound {
            get {
                return ResourceManager.GetString("NoDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开串口成功: {0} 的本地化字符串。
        /// </summary>
        internal static string OpenSerialPortSuccess {
            get {
                return ResourceManager.GetString("OpenSerialPortSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先打开串口 的本地化字符串。
        /// </summary>
        internal static string PleaseOpenSerialPort {
            get {
                return ResourceManager.GetString("PleaseOpenSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择波特率 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectBaudRate {
            get {
                return ResourceManager.GetString("PleaseSelectBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择串口 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectSerialPort {
            get {
                return ResourceManager.GetString("PleaseSelectSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取设备参数失败: {0} 的本地化字符串。
        /// </summary>
        internal static string ReadDeviceParameterFailedWithError {
            get {
                return ResourceManager.GetString("ReadDeviceParameterFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置已修改，请重新连接编码器！ 的本地化字符串。
        /// </summary>
        internal static string ReconnectRequired {
            get {
                return ResourceManager.GetString("ReconnectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在扫描 Slave ID={0} 的本地化字符串。
        /// </summary>
        internal static string ScanningSlaveId {
            get {
                return ResourceManager.GetString("ScanningSlaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口已关闭 的本地化字符串。
        /// </summary>
        internal static string SerialPortClosed {
            get {
                return ResourceManager.GetString("SerialPortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口未打开 的本地化字符串。
        /// </summary>
        internal static string SerialPortNotOpen {
            get {
                return ResourceManager.GetString("SerialPortNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单圈位数已设置为 {0} bit 的本地化字符串。
        /// </summary>
        internal static string SingleTurnBitsSet {
            get {
                return ResourceManager.GetString("SingleTurnBitsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改Slave ID异常: {0} 的本地化字符串。
        /// </summary>
        internal static string SlaveIdChangeException {
            get {
                return ResourceManager.GetString("SlaveIdChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave ID修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string SlaveIdChangeSuccess {
            get {
                return ResourceManager.GetString("SlaveIdChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave ID范围必须是1~127 的本地化字符串。
        /// </summary>
        internal static string SlaveIdOutOfRange {
            get {
                return ResourceManager.GetString("SlaveIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始扫描设备... 的本地化字符串。
        /// </summary>
        internal static string StartScanDevice {
            get {
                return ResourceManager.GetString("StartScanDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止扫描 的本地化字符串。
        /// </summary>
        internal static string StopScanning {
            get {
                return ResourceManager.GetString("StopScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知模式 的本地化字符串。
        /// </summary>
        internal static string UnknownMode {
            get {
                return ResourceManager.GetString("UnknownMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改模式异常: {0} 的本地化字符串。
        /// </summary>
        internal static string WorkModeChangeException {
            get {
                return ResourceManager.GetString("WorkModeChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string WorkModeChangeSuccess {
            get {
                return ResourceManager.GetString("WorkModeChangeSuccess", resourceCulture);
            }
        }
    }
}
