//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncoderModbusTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncoderModbusTool.Properties.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 修改波特率异常: {0} 的本地化字符串。
        /// </summary>
        internal static string BaudRateChangeException {
            get {
                return ResourceManager.GetString("BaudRateChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string BaudRateChangeSuccess {
            get {
                return ResourceManager.GetString("BaudRateChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭串口 的本地化字符串。
        /// </summary>
        internal static string CloseSerialPort {
            get {
                return ResourceManager.GetString("CloseSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接关闭，请重新扫描设备！ 的本地化字符串。
        /// </summary>
        internal static string ConnectionClosedRescan {
            get {
                return ResourceManager.GetString("ConnectionClosedRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续读取已关闭 的本地化字符串。
        /// </summary>
        internal static string ContinuousReadDisabled {
            get {
                return ResourceManager.GetString("ContinuousReadDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续读取已开启 的本地化字符串。
        /// </summary>
        internal static string ContinuousReadEnabled {
            get {
                return ResourceManager.GetString("ContinuousReadEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取设备数据失败 的本地化字符串。
        /// </summary>
        internal static string DeviceDataReadFailed {
            get {
                return ResourceManager.GetString("DeviceDataReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现设备 Slave ID={0} 的本地化字符串。
        /// </summary>
        internal static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备参数读取完成 的本地化字符串。
        /// </summary>
        internal static string DeviceParameterReadComplete {
            get {
                return ResourceManager.GetString("DeviceParameterReadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备(ID={0})参数读取失败 的本地化字符串。
        /// </summary>
        internal static string DeviceParameterReadFailed {
            get {
                return ResourceManager.GetString("DeviceParameterReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CCW(逆时针递增) 的本地化字符串。
        /// </summary>
        internal static string DirectionCCW {
            get {
                return ResourceManager.GetString("DirectionCCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改递增方向异常: {0} 的本地化字符串。
        /// </summary>
        internal static string DirectionChangeFailed {
            get {
                return ResourceManager.GetString("DirectionChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递增方向修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string DirectionChangeSuccess {
            get {
                return ResourceManager.GetString("DirectionChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CW(顺时针递增) 的本地化字符串。
        /// </summary>
        internal static string DirectionCW {
            get {
                return ResourceManager.GetString("DirectionCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭自由模式 的本地化字符串。
        /// </summary>
        internal static string DisableFreeMode {
            get {
                return ResourceManager.GetString("DisableFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启自由模式 的本地化字符串。
        /// </summary>
        internal static string EnableFreeMode {
            get {
                return ResourceManager.GetString("EnableFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接编码器 (ID={0}) 的本地化字符串。
        /// </summary>
        internal static string EncoderConnected {
            get {
                return ResourceManager.GetString("EncoderConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取编码器数据成功 的本地化字符串。
        /// </summary>
        internal static string EncoderDataReadSuccess {
            get {
                return ResourceManager.GetString("EncoderDataReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现编码器，请重新扫描！ (ID={0}) 的本地化字符串。
        /// </summary>
        internal static string EncoderNotFound {
            get {
                return ResourceManager.GetString("EncoderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入Free Mode 的本地化字符串。
        /// </summary>
        internal static string EnterFreeMode {
            get {
                return ResourceManager.GetString("EnterFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出Free Mode 的本地化字符串。
        /// </summary>
        internal static string ExitFreeMode {
            get {
                return ResourceManager.GetString("ExitFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeMode校验错误 的本地化字符串。
        /// </summary>
        internal static string FreeModeCheckError {
            get {
                return ResourceManager.GetString("FreeModeCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeMode校验错误: SUM={0}/{1}, XOR={2}/{3} 的本地化字符串。
        /// </summary>
        internal static string FreeModeCheckErrorDetail {
            get {
                return ResourceManager.GetString("FreeModeCheckErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeMode长度错误: RX Len={0}, DataLen=0x{1} 的本地化字符串。
        /// </summary>
        internal static string FreeModeLengthError {
            get {
                return ResourceManager.GetString("FreeModeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Mode接收超时 的本地化字符串。
        /// </summary>
        internal static string FreeModeReceiveTimeout {
            get {
                return ResourceManager.GetString("FreeModeReceiveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Mode单次读取完成 的本地化字符串。
        /// </summary>
        internal static string FreeModeSingleReadComplete {
            get {
                return ResourceManager.GetString("FreeModeSingleReadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换Free Mode失败: {0} 的本地化字符串。
        /// </summary>
        internal static string FreeModeSwitchFailed {
            get {
                return ResourceManager.GetString("FreeModeSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启后，自由模式将无法使用某些功能！！！ 的本地化字符串。
        /// </summary>
        internal static string FreeModeWarning {
            get {
                return ResourceManager.GetString("FreeModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率错误 的本地化字符串。
        /// </summary>
        internal static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递增方向错误 的本地化字符串。
        /// </summary>
        internal static string InvalidDirection {
            get {
                return ResourceManager.GetString("InvalidDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave ID格式错误 的本地化字符串。
        /// </summary>
        internal static string InvalidSlaveIdFormat {
            get {
                return ResourceManager.GetString("InvalidSlaveIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传时间格式错误 的本地化字符串。
        /// </summary>
        internal static string InvalidUploadTimeFormat {
            get {
                return ResourceManager.GetString("InvalidUploadTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式无效 的本地化字符串。
        /// </summary>
        internal static string InvalidWorkMode {
            get {
                return ResourceManager.GetString("InvalidWorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志已清除 的本地化字符串。
        /// </summary>
        internal static string LogCleared {
            get {
                return ResourceManager.GetString("LogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入地址错误 的本地化字符串。
        /// </summary>
        internal static string ModbusAddressError {
            get {
                return ResourceManager.GetString("ModbusAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC错误 的本地化字符串。
        /// </summary>
        internal static string ModbusCrcError {
            get {
                return ResourceManager.GetString("ModbusCrcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入数据错误 的本地化字符串。
        /// </summary>
        internal static string ModbusDataError {
            get {
                return ResourceManager.GetString("ModbusDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能码错误 的本地化字符串。
        /// </summary>
        internal static string ModbusFunctionCodeError {
            get {
                return ResourceManager.GetString("ModbusFunctionCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modbus响应错误 的本地化字符串。
        /// </summary>
        internal static string ModbusResponseError {
            get {
                return ResourceManager.GetString("ModbusResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应长度错误 的本地化字符串。
        /// </summary>
        internal static string ModbusResponseLengthError {
            get {
                return ResourceManager.GetString("ModbusResponseLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modbus响应超时 的本地化字符串。
        /// </summary>
        internal static string ModbusResponseTimeout {
            get {
                return ResourceManager.GetString("ModbusResponseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多圈位数已设置为 {0} bit 的本地化字符串。
        /// </summary>
        internal static string MultiTurnBitsSet {
            get {
                return ResourceManager.GetString("MultiTurnBitsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现设备 的本地化字符串。
        /// </summary>
        internal static string NoDeviceFound {
            get {
                return ResourceManager.GetString("NoDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开串口 的本地化字符串。
        /// </summary>
        internal static string OpenSerialPort {
            get {
                return ResourceManager.GetString("OpenSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开串口失败: {0} 的本地化字符串。
        /// </summary>
        internal static string OpenSerialPortFailed {
            get {
                return ResourceManager.GetString("OpenSerialPortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开串口成功: {0} 的本地化字符串。
        /// </summary>
        internal static string OpenSerialPortSuccess {
            get {
                return ResourceManager.GetString("OpenSerialPortSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改原点位置异常: {0} 的本地化字符串。
        /// </summary>
        internal static string OriginPositionChangeFailed {
            get {
                return ResourceManager.GetString("OriginPositionChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原点位置修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string OriginPositionChangeSuccess {
            get {
                return ResourceManager.GetString("OriginPositionChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间值 的本地化字符串。
        /// </summary>
        internal static string OriginPositionMiddle {
            get {
                return ResourceManager.GetString("OriginPositionMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原点位置已重置 的本地化字符串。
        /// </summary>
        internal static string OriginPositionResetSuccess {
            get {
                return ResourceManager.GetString("OriginPositionResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0值 的本地化字符串。
        /// </summary>
        internal static string OriginPositionZero {
            get {
                return ResourceManager.GetString("OriginPositionZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新读取参数成功 的本地化字符串。
        /// </summary>
        internal static string ParameterReadAgainSuccess {
            get {
                return ResourceManager.GetString("ParameterReadAgainSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改校验位异常: {0} 的本地化字符串。
        /// </summary>
        internal static string ParityChangeFailed {
            get {
                return ResourceManager.GetString("ParityChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验位修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string ParityChangeSuccess {
            get {
                return ResourceManager.GetString("ParityChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验位为空 的本地化字符串。
        /// </summary>
        internal static string ParityEmpty {
            get {
                return ResourceManager.GetString("ParityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先打开串口 的本地化字符串。
        /// </summary>
        internal static string PleaseOpenSerialPort {
            get {
                return ResourceManager.GetString("PleaseOpenSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择波特率 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectBaudRate {
            get {
                return ResourceManager.GetString("PleaseSelectBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择递增方向 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectDirection {
            get {
                return ResourceManager.GetString("PleaseSelectDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择原点位置 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectOriginPosition {
            get {
                return ResourceManager.GetString("PleaseSelectOriginPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择串口 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectSerialPort {
            get {
                return ResourceManager.GetString("PleaseSelectSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取数据 的本地化字符串。
        /// </summary>
        internal static string ReadData {
            get {
                return ResourceManager.GetString("ReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取设备参数失败: {0} 的本地化字符串。
        /// </summary>
        internal static string ReadDeviceParameterFailedWithError {
            get {
                return ResourceManager.GetString("ReadDeviceParameterFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置已修改，请重新连接编码器！ 的本地化字符串。
        /// </summary>
        internal static string ReconnectRequired {
            get {
                return ResourceManager.GetString("ReconnectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置原点位置异常: {0} 的本地化字符串。
        /// </summary>
        internal static string ResetOriginPositionFailed {
            get {
                return ResourceManager.GetString("ResetOriginPositionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在扫描 Slave ID={0} 的本地化字符串。
        /// </summary>
        internal static string ScanningSlaveId {
            get {
                return ResourceManager.GetString("ScanningSlaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口已关闭 的本地化字符串。
        /// </summary>
        internal static string SerialPortClosed {
            get {
                return ResourceManager.GetString("SerialPortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到串口 {0} 已断开 的本地化字符串。
        /// </summary>
        internal static string SerialPortDisconnected {
            get {
                return ResourceManager.GetString("SerialPortDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 {0} 正在被其他程序使用 的本地化字符串。
        /// </summary>
        internal static string SerialPortInUse {
            get {
                return ResourceManager.GetString("SerialPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口丢失，请重新连接编码器！ 的本地化字符串。
        /// </summary>
        internal static string SerialPortLostReconnect {
            get {
                return ResourceManager.GetString("SerialPortLostReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 {0} 不存在或无法访问 的本地化字符串。
        /// </summary>
        internal static string SerialPortNotFound {
            get {
                return ResourceManager.GetString("SerialPortNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口未打开 的本地化字符串。
        /// </summary>
        internal static string SerialPortNotOpen {
            get {
                return ResourceManager.GetString("SerialPortNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口参数更新成功: {0},{1} 的本地化字符串。
        /// </summary>
        internal static string SerialPortUpdateSuccess {
            get {
                return ResourceManager.GetString("SerialPortUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单圈位数已设置为 {0} bit 的本地化字符串。
        /// </summary>
        internal static string SingleTurnBitsSet {
            get {
                return ResourceManager.GetString("SingleTurnBitsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改Slave ID异常: {0} 的本地化字符串。
        /// </summary>
        internal static string SlaveIdChangeException {
            get {
                return ResourceManager.GetString("SlaveIdChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave ID修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string SlaveIdChangeSuccess {
            get {
                return ResourceManager.GetString("SlaveIdChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave ID范围必须是1~127 的本地化字符串。
        /// </summary>
        internal static string SlaveIdOutOfRange {
            get {
                return ResourceManager.GetString("SlaveIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始连续读取 的本地化字符串。
        /// </summary>
        internal static string StartContinuousReading {
            get {
                return ResourceManager.GetString("StartContinuousReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始Free Mode连续接收 的本地化字符串。
        /// </summary>
        internal static string StartFreeModeContinuousReceiving {
            get {
                return ResourceManager.GetString("StartFreeModeContinuousReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始读取 的本地化字符串。
        /// </summary>
        internal static string StartReading {
            get {
                return ResourceManager.GetString("StartReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始接收 的本地化字符串。
        /// </summary>
        internal static string StartReceiving {
            get {
                return ResourceManager.GetString("StartReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始扫描设备... 的本地化字符串。
        /// </summary>
        internal static string StartScanDevice {
            get {
                return ResourceManager.GetString("StartScanDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止连续读取 的本地化字符串。
        /// </summary>
        internal static string StopContinuousRead {
            get {
                return ResourceManager.GetString("StopContinuousRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止连续读取失败: {0} 的本地化字符串。
        /// </summary>
        internal static string StopContinuousReadFailed {
            get {
                return ResourceManager.GetString("StopContinuousReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止Free Mode接收 的本地化字符串。
        /// </summary>
        internal static string StopFreeModeReceiving {
            get {
                return ResourceManager.GetString("StopFreeModeReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止读取 的本地化字符串。
        /// </summary>
        internal static string StopReading {
            get {
                return ResourceManager.GetString("StopReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止接收 的本地化字符串。
        /// </summary>
        internal static string StopReceiving {
            get {
                return ResourceManager.GetString("StopReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止扫描 的本地化字符串。
        /// </summary>
        internal static string StopScanning {
            get {
                return ResourceManager.GetString("StopScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知模式 的本地化字符串。
        /// </summary>
        internal static string UnknownMode {
            get {
                return ResourceManager.GetString("UnknownMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知原点位置 的本地化字符串。
        /// </summary>
        internal static string UnknownOriginPosition {
            get {
                return ResourceManager.GetString("UnknownOriginPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知校验方式 的本地化字符串。
        /// </summary>
        internal static string UnknownParity {
            get {
                return ResourceManager.GetString("UnknownParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在更新串口参数... 的本地化字符串。
        /// </summary>
        internal static string UpdatingSerialPort {
            get {
                return ResourceManager.GetString("UpdatingSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改上传时间异常: {0} 的本地化字符串。
        /// </summary>
        internal static string UploadTimeChangeFailed {
            get {
                return ResourceManager.GetString("UploadTimeChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传时间修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string UploadTimeChangeSuccess {
            get {
                return ResourceManager.GetString("UploadTimeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传时间为空 的本地化字符串。
        /// </summary>
        internal static string UploadTimeEmpty {
            get {
                return ResourceManager.GetString("UploadTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传时间超出范围 的本地化字符串。
        /// </summary>
        internal static string UploadTimeOutOfRange {
            get {
                return ResourceManager.GetString("UploadTimeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改模式异常: {0} 的本地化字符串。
        /// </summary>
        internal static string WorkModeChangeException {
            get {
                return ResourceManager.GetString("WorkModeChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式修改成功: {0} 的本地化字符串。
        /// </summary>
        internal static string WorkModeChangeSuccess {
            get {
                return ResourceManager.GetString("WorkModeChangeSuccess", resourceCulture);
            }
        }
    }
}
