//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncoderModbusTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncoderModbusTool.Properties.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改波特率异常: {0}.
        /// </summary>
        internal static string BaudRateChangeException {
            get {
                return ResourceManager.GetString("BaudRateChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波特率修改成功: {0}.
        /// </summary>
        internal static string BaudRateChangeSuccess {
            get {
                return ResourceManager.GetString("BaudRateChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接关闭，请重新扫描设备！.
        /// </summary>
        internal static string ConnectionClosedRescan {
            get {
                return ResourceManager.GetString("ConnectionClosedRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连续读取已关闭.
        /// </summary>
        internal static string ContinuousReadDisabled {
            get {
                return ResourceManager.GetString("ContinuousReadDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连续读取已开启.
        /// </summary>
        internal static string ContinuousReadEnabled {
            get {
                return ResourceManager.GetString("ContinuousReadEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现设备 Slave ID={0}.
        /// </summary>
        internal static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备参数读取完成.
        /// </summary>
        internal static string DeviceParameterReadComplete {
            get {
                return ResourceManager.GetString("DeviceParameterReadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备(ID={0})参数读取失败.
        /// </summary>
        internal static string DeviceParameterReadFailed {
            get {
                return ResourceManager.GetString("DeviceParameterReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭自由模式.
        /// </summary>
        internal static string DisableFreeMode {
            get {
                return ResourceManager.GetString("DisableFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启自由模式.
        /// </summary>
        internal static string EnableFreeMode {
            get {
                return ResourceManager.GetString("EnableFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已连接编码器 (ID={0}).
        /// </summary>
        internal static string EncoderConnected {
            get {
                return ResourceManager.GetString("EncoderConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现编码器，请重新扫描！ (ID={0}).
        /// </summary>
        internal static string EncoderNotFound {
            get {
                return ResourceManager.GetString("EncoderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入Free Mode.
        /// </summary>
        internal static string EnterFreeMode {
            get {
                return ResourceManager.GetString("EnterFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出Free Mode.
        /// </summary>
        internal static string ExitFreeMode {
            get {
                return ResourceManager.GetString("ExitFreeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeMode校验错误.
        /// </summary>
        internal static string FreeModeCheckError {
            get {
                return ResourceManager.GetString("FreeModeCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeMode校验错误: SUM={0}/{1}, XOR={2}/{3}.
        /// </summary>
        internal static string FreeModeCheckErrorDetail {
            get {
                return ResourceManager.GetString("FreeModeCheckErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeMode长度错误: RX Len={0}, DataLen=0x{1}.
        /// </summary>
        internal static string FreeModeLengthError {
            get {
                return ResourceManager.GetString("FreeModeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Mode接收超时.
        /// </summary>
        internal static string FreeModeReceiveTimeout {
            get {
                return ResourceManager.GetString("FreeModeReceiveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换Free Mode失败: {0}.
        /// </summary>
        internal static string FreeModeSwitchFailed {
            get {
                return ResourceManager.GetString("FreeModeSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启后，自由模式将无法使用某些功能！！！.
        /// </summary>
        internal static string FreeModeWarning {
            get {
                return ResourceManager.GetString("FreeModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波特率错误.
        /// </summary>
        internal static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave ID格式错误.
        /// </summary>
        internal static string InvalidSlaveIdFormat {
            get {
                return ResourceManager.GetString("InvalidSlaveIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作模式无效.
        /// </summary>
        internal static string InvalidWorkMode {
            get {
                return ResourceManager.GetString("InvalidWorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志已清除.
        /// </summary>
        internal static string LogCleared {
            get {
                return ResourceManager.GetString("LogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多圈位数已设置为 {0} bit.
        /// </summary>
        internal static string MultiTurnBitsSet {
            get {
                return ResourceManager.GetString("MultiTurnBitsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现设备.
        /// </summary>
        internal static string NoDeviceFound {
            get {
                return ResourceManager.GetString("NoDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开串口成功: {0}.
        /// </summary>
        internal static string OpenSerialPortSuccess {
            get {
                return ResourceManager.GetString("OpenSerialPortSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新读取参数成功.
        /// </summary>
        internal static string ParameterReadAgainSuccess {
            get {
                return ResourceManager.GetString("ParameterReadAgainSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先打开串口.
        /// </summary>
        internal static string PleaseOpenSerialPort {
            get {
                return ResourceManager.GetString("PleaseOpenSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择波特率.
        /// </summary>
        internal static string PleaseSelectBaudRate {
            get {
                return ResourceManager.GetString("PleaseSelectBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择串口.
        /// </summary>
        internal static string PleaseSelectSerialPort {
            get {
                return ResourceManager.GetString("PleaseSelectSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取设备参数失败: {0}.
        /// </summary>
        internal static string ReadDeviceParameterFailedWithError {
            get {
                return ResourceManager.GetString("ReadDeviceParameterFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置已修改，请重新连接编码器！.
        /// </summary>
        internal static string ReconnectRequired {
            get {
                return ResourceManager.GetString("ReconnectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在扫描 Slave ID={0}.
        /// </summary>
        internal static string ScanningSlaveId {
            get {
                return ResourceManager.GetString("ScanningSlaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口已关闭.
        /// </summary>
        internal static string SerialPortClosed {
            get {
                return ResourceManager.GetString("SerialPortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口未打开.
        /// </summary>
        internal static string SerialPortNotOpen {
            get {
                return ResourceManager.GetString("SerialPortNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单圈位数已设置为 {0} bit.
        /// </summary>
        internal static string SingleTurnBitsSet {
            get {
                return ResourceManager.GetString("SingleTurnBitsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改Slave ID异常: {0}.
        /// </summary>
        internal static string SlaveIdChangeException {
            get {
                return ResourceManager.GetString("SlaveIdChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave ID修改成功: {0}.
        /// </summary>
        internal static string SlaveIdChangeSuccess {
            get {
                return ResourceManager.GetString("SlaveIdChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave ID范围必须是1~127.
        /// </summary>
        internal static string SlaveIdOutOfRange {
            get {
                return ResourceManager.GetString("SlaveIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始读取.
        /// </summary>
        internal static string StartReading {
            get {
                return ResourceManager.GetString("StartReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始接收.
        /// </summary>
        internal static string StartReceiving {
            get {
                return ResourceManager.GetString("StartReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始扫描设备....
        /// </summary>
        internal static string StartScanDevice {
            get {
                return ResourceManager.GetString("StartScanDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止连续读取.
        /// </summary>
        internal static string StopContinuousRead {
            get {
                return ResourceManager.GetString("StopContinuousRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止连续读取失败: {0}.
        /// </summary>
        internal static string StopContinuousReadFailed {
            get {
                return ResourceManager.GetString("StopContinuousReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止扫描.
        /// </summary>
        internal static string StopScanning {
            get {
                return ResourceManager.GetString("StopScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知模式.
        /// </summary>
        internal static string UnknownMode {
            get {
                return ResourceManager.GetString("UnknownMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改模式异常: {0}.
        /// </summary>
        internal static string WorkModeChangeException {
            get {
                return ResourceManager.GetString("WorkModeChangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作模式修改成功: {0}.
        /// </summary>
        internal static string WorkModeChangeSuccess {
            get {
                return ResourceManager.GetString("WorkModeChangeSuccess", resourceCulture);
            }
        }
    }
}
